
export const foodName = [
    {
        id: 1,
        name: 'Burgers',
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613400445/close-up-photo-of-burger-3915906-scaled_am0nnr.jpg"
    },
    {
        id: 2,
        name: "Pizza",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613400444/depositphotos_41466555-stock-photo-image-of-slice-of-pizza_axgj5d.jpg",
    },
    {
        id: 3,
        name: "Snacks",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613400447/mnet_156037_saltysnackslisting_xukfav.png"
    }, {
        id: 4,
        name: "Sushi",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613400446/GettyImages-126553802-56a541cb3df78cf772875a68_vtlqww.jpg"
    },
    {
        id: 5,
        name: "Hot Dogs",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613843469/download_2_nyc7dv.jpg"
    },
    {
        id: 6,
        name: "Pasta",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613843469/download_3_hhopgr.jpg"
    }
]


export const foodItems = [
    {
        id: 1,
        name: "Classic Smashed",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613400445/close-up-photo-of-burger-3915906-scaled_am0nnr.jpg",
        description: "A hamburger (also burger for short) is a sandwich consisting of one or more cooked patties of ground meat, usually beef, placed inside a sliced bread roll or bun. The patty may be pan fried, grilled, smoked or flame broiled.",
        delivery: "25-30min",
        category: "Burgers",
        rating: "4.7",
        price: 50,
    },
    {
        id: 2,
        name: "Pizza Dough",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613400444/depositphotos_41466555-stock-photo-image-of-slice-of-pizza_axgj5d.jpg",
        delivery: "45-60min",
        category: "Pizza",
        description:"Pizza, dish of Italian origin consisting of a flattened disk of bread dough topped with some combination of olive oil, oregano, tomato, olives, mozzarella or other cheese, and many other ingredients.",
        rating: "4.3",
        price: 150,
    },
    {
        id: 3,
        name: "Sushi Rolls",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613400446/GettyImages-126553802-56a541cb3df78cf772875a68_vtlqww.jpg",
        delivery: "20-30min",
        category: "Sushi",
        description:"Sushi, a staple rice dish of Japanese cuisine, consisting of cooked rice flavoured with vinegar and a variety of vegetable, egg, or raw seafood garnishes and served cold",
        rating: "4.9",
        price: 20,
    },
    {
        id: 4,
        name: "Homemade Hot Dogs",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613400447/mnet_156037_saltysnackslisting_xukfav.png",
        delivery: "25-30min",
        category: "Hot Dogs",
        description:"A snack is a small portion of food generally eaten between meals. Snacks come in a variety of forms including packaged snack foods and other processed foods",
        rating: "4.5",
        price: 100,
    },
    {
        id: 5,
        name: "Mondelez",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613400447/mnet_156037_saltysnackslisting_xukfav.png",
        delivery: "15-30min",
        category: "Snacks",
        description:"Hot dogs means a whole, cured, cooked sausage that is skinless or stuffed in a casing, that may be known as a frankfurter, frank, furter, wiener, red hot, vienna, bologna, garlic bologna, or knockwurst, and that may be served in a bun or roll",
        rating: "4.1",
        price: 30,
    },
    {
        id: 6,
        name: "Masala Pasta",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613843469/download_3_hhopgr.jpg",
        delivery: "25-30min",        
        category: "Pasta",
        description:"Pasta is a type of food typically made from an unleavened dough of wheat flour mixed with water or eggs, and formed into sheets or other shapes, then cooked by boiling or baking",
        rating: "4.7",
        price: 250,
    },
    {
        id: 7,
        name: "Spicy Penne Pasta",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613902289/download_4_vgzrqg.jpg",
        delivery: "25-30min",
        category: "Pasta",
        description:"Pasta is a type of food typically made from an unleavened dough of wheat flour mixed with water or eggs, and formed into sheets or other shapes, then cooked by boiling or baking",
        rating: "4.7",
        price: 250,
    },
    {
        id: 8,
        name: "Pantry Pasta",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613902289/download_5_fu5ihh.jpg",
        delivery: "25-30min",
        category: "Pasta",
        description:"Pasta is a type of food typically made from an unleavened dough of wheat flour mixed with water or eggs, and formed into sheets or other shapes, then cooked by boiling or baking",
        rating: "4.7",
        price: 250,
    },
    {
        id: 9,
        name: "Fresh and Easy Veg Pasta",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613902289/masala-pasta_cw03vz.jpg",
        delivery: "25-30min",
        category: "Pasta",
        description:"Pasta is a type of food typically made from an unleavened dough of wheat flour mixed with water or eggs, and formed into sheets or other shapes, then cooked by boiling or baking",
        rating: "4.7",
        price: 250,
    },
    {
        id: 10,
        name: "Classic Hot Dog",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613902441/download_15_tk1yx6.jpg",
        delivery: "25-30min",
        category: "Hot Dogs",
        description:"Pasta is a type of food typically made from an unleavened dough of wheat flour mixed with water or eggs, and formed into sheets or other shapes, then cooked by boiling or baking",
        rating: "4.7",
        price: 250,
    },
    {
        id: 11,
        name: "Grilled Hot Dog",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613902441/download_17_vhwub3.jpg",
        delivery: "25-30min",
        category: "Hot Dogs",
        description:"Pasta is a type of food typically made from an unleavened dough of wheat flour mixed with water or eggs, and formed into sheets or other shapes, then cooked by boiling or baking",
        rating: "4.7",
        price: 250,
    },
    {
        id: 12,
        name: "Air Fryer Hot Dog",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613902441/download_16_rdhio1.jpg",
        delivery: "25-30min",
        category: "Hot Dogs",
        description:"Pasta is a type of food typically made from an unleavened dough of wheat flour mixed with water or eggs, and formed into sheets or other shapes, then cooked by boiling or baking",
        rating: "4.7",
        price: 250,
    },
    {
        id: 13,
        name: "Garlic Burger",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613902328/download_8_tmfraw.jpg",
        description: "A hamburger (also burger for short) is a sandwich consisting of one or more cooked patties of ground meat, usually beef, placed inside a sliced bread roll or bun. The patty may be pan fried, grilled, smoked or flame broiled.",
        delivery: "25-30min",
        category: "Burgers",
        rating: "4.7",
        price: 50,
    },
    {
        id: 14,
        name: "Juiciest Burger",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613902328/download_6_l1ybm3.jpg",
        delivery: "45-60min",
        category: "Burgers",
        description:"Pizza, dish of Italian origin consisting of a flattened disk of bread dough topped with some combination of olive oil, oregano, tomato, olives, mozzarella or other cheese, and many other ingredients.",
        rating: "4.3",
        price: 150,
    },
    {
        id: 15,
        name: "All American",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613902328/download_7_y2po0i.jpg",
        delivery: "20-30min",
        category: "Burgers",
        description:"Sushi, a staple rice dish of Japanese cuisine, consisting of cooked rice flavoured with vinegar and a variety of vegetable, egg, or raw seafood garnishes and served cold",
        rating: "4.9",
        price: 20,
    },
    {
        id: 16,
        name: "Lekki Sushi",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613902405/download_12_oa5tzb.jpg",
        delivery: "25-30min",
        category: "Sushi",
        description:"A snack is a small portion of food generally eaten between meals. Snacks come in a variety of forms including packaged snack foods and other processed foods",
        rating: "4.5",
        price: 100,
    },
    {
        id: 17,
        name: "Maki Sushi Roll",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613902405/download_14_uftl41.jpg",
        delivery: "15-30min",
        category: "Sushi",
        description:"Hot dogs means a whole, cured, cooked sausage that is skinless or stuffed in a casing, that may be known as a frankfurter, frank, furter, wiener, red hot, vienna, bologna, garlic bologna, or knockwurst, and that may be served in a bun or roll",
        rating: "4.1",
        price: 30,
    },
    {
        id: 18,
        name: "Peanut Tofu Sushi",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613902405/download_13_q9pker.jpg",
        delivery: "25-30min",
        category: "Sushi",
        description:"Pasta is a type of food typically made from an unleavened dough of wheat flour mixed with water or eggs, and formed into sheets or other shapes, then cooked by boiling or baking",
        rating: "4.7",
        price: 250,
    },
    {
        id: 19,
        name: "Mozzarella Cheese",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613902365/download_10_nkshgm.jpg",
        delivery: "25-30min",
        category: "Pizza",
        description:"Pasta is a type of food typically made from an unleavened dough of wheat flour mixed with water or eggs, and formed into sheets or other shapes, then cooked by boiling or baking",
        rating: "4.7",
        price: 250,
    },
    {
        id: 20,
        name: "Gluten Pizza",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613902365/download_9_z2oq4c.jpg",
        delivery: "25-30min",
        category: "Pizza",
        description:"Pasta is a type of food typically made from an unleavened dough of wheat flour mixed with water or eggs, and formed into sheets or other shapes, then cooked by boiling or baking",
        rating: "4.7",
        price: 250,
    },
    {
        id: 21,
        name: "Hawaiian Pizza",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613902365/download_11_szdzcq.jpg",
        delivery: "25-30min",
        category: "Pizza",
        description:"Pasta is a type of food typically made from an unleavened dough of wheat flour mixed with water or eggs, and formed into sheets or other shapes, then cooked by boiling or baking",
        rating: "4.7",
        price: 250,
    },
    {
        id: 22,
        name: "Candie Snacks",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613902490/download_20_ew27pk.jpg",
        delivery: "25-30min",
        category: "Snacks",
        description:"Pasta is a type of food typically made from an unleavened dough of wheat flour mixed with water or eggs, and formed into sheets or other shapes, then cooked by boiling or baking",
        rating: "4.7",
        price: 250,
    },
    {
        id: 23,
        name: "Flavorful Snack",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613902490/download_18_ar8yzf.jpg",
        delivery: "25-30min",
        category: "Snacks",
        description:"Pasta is a type of food typically made from an unleavened dough of wheat flour mixed with water or eggs, and formed into sheets or other shapes, then cooked by boiling or baking",
        rating: "4.7",
        price: 250,
    },
    {
        id: 24,
        name: "Banana Snacks",
        image: "https://res.cloudinary.com/doouwbecx/image/upload/v1613902490/download_19_sjvpfy.jpg",
        delivery: "25-30min",
        category: "Snacks",
        description:"Pasta is a type of food typically made from an unleavened dough of wheat flour mixed with water or eggs, and formed into sheets or other shapes, then cooked by boiling or baking",
        rating: "4.7",
        price: 250,
    },
]